print value `vars.FAIL_MAIN`
Signed-off-by: Bryant Finney <bryant.finney@outlook.com>

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -6,7 +6,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - if: vars.FAIL_MAIN
-        run: exit 1
+        run: |
+          printf 'vars.FAIL_MAIN=%s\n' "${{ vars.FAIL_MAIN }}"
+          exit 1
 
       - run: echo "success ✅"
 
